/** 티커 → 영어 회사명. 종목 찾기 검색창이 영어로 쳐도 찾히게 하려고 둔다.
 *  `scores.json`의 `name`은 한글 표기만 있다(토스증권 API가 그렇게 준다).
 *  여기 값은 data-pipeline/data/universe_us.json(영어 회사명이 있는 정적
 *  참조 파일)에서 한 번 옮겨온 스냅샷이다 — 배치를 새로 돌리지 않아도 되지만,
 *  그만큼 유니버스가 바뀌면(신규 편입·상장폐지) 손으로 다시 맞춰야 한다. */
export const COMPANY_NAME_EN: Record<string, string> = {
  "A": "Agilent Technologies",
  "AAPL": "Apple Inc.",
  "ABBV": "AbbVie",
  "ABT": "Abbott Laboratories",
  "ACGL": "Arch Capital Group",
  "ACN": "Accenture",
  "ADBE": "Adobe Inc.",
  "ADI": "Analog Devices",
  "ADM": "Archer Daniels Midland",
  "ADSK": "Autodesk",
  "AEE": "Ameren",
  "AES": "AES Corporation",
  "AIG": "American International Group",
  "AIZ": "Assurant",
  "AJG": "Arthur J. Gallagher & Co.",
  "ALB": "Albemarle Corporation",
  "ALGN": "Align Technology",
  "ALLE": "Allegion",
  "ALNY": "Alnylam Pharmaceuticals, Inc.",
  "AMAT": "Applied Materials",
  "AMCR": "Amcor",
  "AMD": "Advanced Micro Devices",
  "AME": "Ametek",
  "AMGN": "Amgen",
  "AMP": "Ameriprise Financial",
  "AMT": "American Tower",
  "AMZN": "Amazon",
  "ANET": "Arista Networks",
  "AON": "Aon plc",
  "AOS": "A. O. Smith",
  "APH": "Amphenol",
  "APO": "Apollo Global Management",
  "APTV": "Aptiv",
  "ARES": "Ares Management",
  "ATO": "Atmos Energy",
  "AVGO": "Broadcom",
  "AVY": "Avery Dennison",
  "AWK": "American Water Works",
  "AXON": "Axon Enterprise",
  "AZO": "AutoZone",
  "BA": "Boeing",
  "BAC": "Bank of America",
  "BAX": "Baxter International",
  "BBY": "Best Buy",
  "BEN": "Franklin Resources",
  "BLDR": "Builders FirstSource",
  "BMY": "Bristol Myers Squibb",
  "BR": "Broadridge Financial Solutions",
  "BRO": "Brown & Brown",
  "BSX": "Boston Scientific",
  "BX": "Blackstone Inc.",
  "C": "Citigroup",
  "CAH": "Cardinal Health",
  "CARR": "Carrier Global",
  "CAT": "Caterpillar Inc.",
  "CB": "Chubb Limited",
  "CBRE": "CBRE Group",
  "CCI": "Crown Castle",
  "CCL": "Carnival Corporation",
  "CDNS": "Cadence Design Systems",
  "CDW": "CDW Corporation",
  "CEG": "Constellation Energy",
  "CF": "CF Industries",
  "CFG": "Citizens Financial Group",
  "CHD": "Church & Dwight",
  "CHRW": "C.H. Robinson",
  "CHTR": "Charter Communications",
  "CI": "Cigna",
  "CIEN": "Ciena",
  "CINF": "Cincinnati Financial",
  "CL": "Colgate-Palmolive",
  "CLX": "Clorox",
  "CMCSA": "Comcast",
  "CME": "CME Group",
  "CMG": "Chipotle Mexican Grill",
  "CMI": "Cummins",
  "CNC": "Centene Corporation",
  "CNP": "CenterPoint Energy",
  "COF": "Capital One",
  "COIN": "Coinbase",
  "COO": "Cooper Companies (The)",
  "COR": "Cencora",
  "COST": "Costco",
  "CPAY": "Corpay",
  "CRL": "Charles River Laboratories",
  "CRM": "Salesforce",
  "CSCO": "Cisco",
  "CSGP": "CoStar Group",
  "CSX": "CSX Corporation",
  "CTAS": "Cintas",
  "CTSH": "Cognizant",
  "CTVA": "Corteva",
  "CVS": "CVS Health",
  "CVX": "Chevron Corporation",
  "D": "Dominion Energy",
  "DAL": "Delta Air Lines",
  "DASH": "DoorDash",
  "DDOG": "Datadog",
  "DECK": "Deckers Brands",
  "DELL": "Dell Technologies",
  "DG": "Dollar General",
  "DGX": "Quest Diagnostics",
  "DHR": "Danaher Corporation",
  "DLR": "Digital Realty",
  "DOC": "Healthpeak Properties",
  "DOW": "Dow Inc.",
  "DVA": "DaVita",
  "DXCM": "Dexcom",
  "EBAY": "eBay Inc.",
  "ECHO": "EchoStar",
  "ECL": "Ecolab",
  "EFX": "Equifax",
  "EG": "Everest Group",
  "EIX": "Edison International",
  "EL": "Estée Lauder Companies (The)",
  "ELV": "Elevance Health",
  "EME": "Emcor",
  "EMR": "Emerson Electric",
  "EQIX": "Equinix",
  "EQT": "EQT Corporation",
  "ERIE": "Erie Indemnity",
  "ES": "Eversource Energy",
  "ESS": "Essex Property Trust",
  "ETR": "Entergy",
  "EVRG": "Evergy",
  "EW": "Edwards Lifesciences",
  "EXC": "Exelon",
  "EXE": "Expand Energy",
  "EXPD": "Expeditors International",
  "EXPE": "Expedia Group",
  "EXR": "Extra Space Storage",
  "F": "Ford Motor Company",
  "FAST": "Fastenal",
  "FCX": "Freeport-McMoRan",
  "FDS": "FactSet",
  "FDX": "FedEx",
  "FE": "FirstEnergy",
  "FFIV": "F5, Inc.",
  "FICO": "Fair Isaac",
  "FISV": "Fiserv",
  "FIX": "Comfort Systems USA",
  "FLEX": "Flex Ltd.",
  "FOX": "Fox Corporation (Class B)",
  "FOXA": "Fox Corporation (Class A)",
  "FRT": "Federal Realty Investment Trust",
  "FSLR": "First Solar",
  "FTNT": "Fortinet",
  "FTV": "Fortive",
  "GD": "General Dynamics",
  "GDDY": "GoDaddy",
  "GEN": "Gen Digital",
  "GILD": "Gilead Sciences",
  "GIS": "General Mills",
  "GM": "General Motors",
  "GNRC": "Generac",
  "GOOG": "Alphabet Inc. (Class C)",
  "GOOGL": "Alphabet Inc. (Class A)",
  "GPN": "Global Payments",
  "GRMN": "Garmin",
  "GWW": "W. W. Grainger",
  "HAS": "Hasbro",
  "HBAN": "Huntington Bancshares",
  "HCA": "HCA Healthcare",
  "HD": "Home Depot (The)",
  "HII": "Huntington Ingalls Industries",
  "HLT": "Hilton Worldwide",
  "HOOD": "Robinhood Markets",
  "HPE": "Hewlett Packard Enterprise",
  "HPQ": "HP Inc.",
  "HSIC": "Henry Schein",
  "HST": "Host Hotels & Resorts",
  "HSY": "Hershey Company (The)",
  "HUBB": "Hubbell Incorporated",
  "HUM": "Humana",
  "HWM": "Howmet Aerospace",
  "IBKR": "Interactive Brokers",
  "IBM": "IBM",
  "IDXX": "Idexx Laboratories",
  "IEX": "IDEX Corporation",
  "IFF": "International Flavors & Fragrances",
  "INCY": "Incyte",
  "INTC": "Intel",
  "INTU": "Intuit",
  "IQV": "IQVIA",
  "IR": "Ingersoll Rand",
  "IRM": "Iron Mountain",
  "ISRG": "Intuitive Surgical",
  "ITW": "Illinois Tool Works",
  "IVZ": "Invesco",
  "JBL": "Jabil",
  "JKHY": "Jack Henry & Associates",
  "JPM": "JPMorgan Chase",
  "KDP": "Keurig Dr Pepper",
  "KEY": "KeyCorp",
  "KEYS": "Keysight Technologies",
  "KIM": "Kimco Realty",
  "KKR": "KKR & Co.",
  "KMB": "Kimberly-Clark",
  "KMI": "Kinder Morgan",
  "KO": "Coca-Cola Company (The)",
  "KR": "Kroger",
  "L": "Loews Corporation",
  "LDOS": "Leidos",
  "LH": "Labcorp",
  "LII": "Lennox International",
  "LIN": "Linde plc",
  "LITE": "Lumentum",
  "LMT": "Lockheed Martin",
  "LNT": "Alliant Energy",
  "LOW": "Lowe's",
  "LRCX": "Lam Research",
  "LULU": "Lululemon Athletica",
  "LUV": "Southwest Airlines",
  "LVS": "Las Vegas Sands",
  "LYB": "LyondellBasell",
  "LYV": "Live Nation Entertainment",
  "MA": "Mastercard",
  "MAR": "Marriott International",
  "MAS": "Masco",
  "MCD": "McDonald's",
  "MCHP": "Microchip Technology",
  "MCK": "McKesson Corporation",
  "MCO": "Moody's Corporation",
  "MDLZ": "Mondelez International",
  "MDT": "Medtronic",
  "MELI": "Mercado Libre, Inc",
  "META": "Meta Platforms",
  "MGM": "MGM Resorts",
  "MKC": "McCormick & Company",
  "MLM": "Martin Marietta Materials",
  "MMM": "3M",
  "MNST": "Monster Beverage",
  "MO": "Altria",
  "MOS": "Mosaic Company (The)",
  "MPC": "Marathon Petroleum",
  "MPWR": "Monolithic Power Systems",
  "MRK": "Merck & Co.",
  "MRNA": "Moderna",
  "MRVL": "Marvell Technology",
  "MSCI": "MSCI Inc.",
  "MSFT": "Microsoft",
  "MSI": "Motorola Solutions",
  "MSTR": "Strategy Inc Common Stock Class A",
  "MTB": "M&T Bank",
  "MTD": "Mettler Toledo",
  "MU": "Micron Technology",
  "NDAQ": "Nasdaq, Inc.",
  "NDSN": "Nordson Corporation",
  "NEM": "Newmont",
  "NFLX": "Netflix",
  "NI": "NiSource",
  "NKE": "Nike, Inc.",
  "NOC": "Northrop Grumman",
  "NOW": "ServiceNow",
  "NRG": "NRG Energy",
  "NSC": "Norfolk Southern",
  "NTAP": "NetApp",
  "NTRS": "Northern Trust",
  "NUE": "Nucor",
  "NVDA": "Nvidia",
  "NXPI": "NXP Semiconductors",
  "O": "Realty Income",
  "OKE": "Oneok",
  "OMC": "Omnicom Group",
  "ON": "ON Semiconductor",
  "ORCL": "Oracle Corporation",
  "ORLY": "O’Reilly Automotive",
  "OTIS": "Otis Worldwide",
  "OXY": "Occidental Petroleum",
  "PANW": "Palo Alto Networks",
  "PAYX": "Paychex",
  "PCG": "PG&E Corporation",
  "PEG": "Public Service Enterprise Group",
  "PEP": "PepsiCo",
  "PFE": "Pfizer",
  "PG": "Procter & Gamble",
  "PGR": "Progressive Corporation",
  "PH": "Parker Hannifin",
  "PKG": "Packaging Corporation of America",
  "PLD": "Prologis",
  "PLTR": "Palantir Technologies",
  "PM": "Philip Morris International",
  "PNC": "PNC Financial Services",
  "PNR": "Pentair",
  "PNW": "Pinnacle West Capital",
  "PODD": "Insulet Corporation",
  "PPL": "PPL Corporation",
  "PRU": "Prudential Financial",
  "PTC": "PTC Inc.",
  "PWR": "Quanta Services",
  "PYPL": "PayPal",
  "QCOM": "Qualcomm",
  "RCL": "Royal Caribbean Group",
  "REGN": "Regeneron Pharmaceuticals",
  "RKLB": "Rocket Lab Corporation Common Stock",
  "RL": "Ralph Lauren Corporation",
  "RMD": "ResMed",
  "ROL": "Rollins, Inc.",
  "ROP": "Roper Technologies",
  "RSG": "Republic Services",
  "RTX": "RTX Corporation",
  "RVTY": "Revvity",
  "SBAC": "SBA Communications",
  "SBUX": "Starbucks",
  "SCHW": "Charles Schwab Corporation",
  "SMCI": "Supermicro",
  "SNPS": "Synopsys",
  "SO": "Southern Company",
  "SPG": "Simon Property Group",
  "SPGI": "S&P Global",
  "SRE": "Sempra",
  "STE": "Steris",
  "STLD": "Steel Dynamics",
  "STT": "State Street Corporation",
  "STX": "Seagate Technology",
  "STZ": "Constellation Brands",
  "SWKS": "Skyworks Solutions",
  "SYK": "Stryker Corporation",
  "SYY": "Sysco",
  "T": "AT&T",
  "TAP": "Molson Coors Beverage Company",
  "TDG": "TransDigm Group",
  "TDY": "Teledyne Technologies",
  "TECH": "Bio-Techne",
  "TEL": "TE Connectivity",
  "TER": "Teradyne",
  "TGT": "Target Corporation",
  "TMO": "Thermo Fisher Scientific",
  "TMUS": "T-Mobile US",
  "TPL": "Texas Pacific Land Corporation",
  "TPR": "Tapestry, Inc.",
  "TRGP": "Targa Resources",
  "TRMB": "Trimble Inc.",
  "TROW": "T. Rowe Price",
  "TSCO": "Tractor Supply",
  "TSLA": "Tesla, Inc.",
  "TSN": "Tyson Foods",
  "TT": "Trane Technologies",
  "TTD": "Trade Desk (The)",
  "TTWO": "Take-Two Interactive",
  "TXN": "Texas Instruments",
  "TYL": "Tyler Technologies",
  "UAL": "United Airlines Holdings",
  "UBER": "Uber",
  "UDR": "UDR, Inc.",
  "UHS": "Universal Health Services",
  "ULTA": "Ulta Beauty",
  "UNH": "UnitedHealth Group",
  "UNP": "Union Pacific Corporation",
  "UPS": "United Parcel Service",
  "USB": "U.S. Bancorp",
  "V": "Visa Inc.",
  "VMC": "Vulcan Materials Company",
  "VRSK": "Verisk Analytics",
  "VRT": "Vertiv",
  "VRTX": "Vertex Pharmaceuticals",
  "VST": "Vistra Corp.",
  "VTR": "Ventas",
  "VTRS": "Viatris",
  "VZ": "Verizon",
  "WAB": "Wabtec",
  "WAT": "Waters Corporation",
  "WBD": "Warner Bros. Discovery",
  "WDAY": "Workday, Inc.",
  "WDC": "Western Digital",
  "WM": "Waste Management",
  "WMB": "Williams Companies",
  "WMT": "Walmart",
  "WRB": "W. R. Berkley Corporation",
  "WSM": "Williams-Sonoma, Inc.",
  "WST": "West Pharmaceutical Services",
  "WTW": "Willis Towers Watson",
  "WY": "Weyerhaeuser",
  "XYL": "Xylem Inc.",
  "XYZ": "Block, Inc.",
  "YUM": "Yum! Brands",
  "ZBH": "Zimmer Biomet",
  "ZBRA": "Zebra Technologies",
  "ZTS": "Zoetis"
};
